apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra-deployment
  labels:
    app: sinatra
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sinatra
  template:
    metadata:
      labels:
        app: sinatra
        version: v1
    spec:
      containers:
      - name: sinatra
        image: divyangjp/dp-sinatra:89c7cfb
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
