apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: health-backendconfig
spec:
  healthCheck:
    type: HTTP
    requestPath: /health
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: health-backendconfig-8080
spec:
  healthCheck:
    type: HTTP
    requestPath: /health
    port: 8080
