apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
  labels:
    app: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: dfranciswoolies/ciarecruitment-bestapiever:247904
        ports:
        - containerPort: 80
      # CRUDE way to access secrets
      # csi-driver is best practice to access secrets
      # but gke Autopilot mode doesn't allow priviledged containers
      - name: secrets
        image: gcr.io/google.com/cloudsdktool/cloud-sdk
        args:
        - echo "APIKEY=$(gcloud secrets versions access latest --secret=\"APIKEY\")" >> apikey.env
        volumeMounts:
        - name: config-data
          mountPath: /data
      volumes:
      - name: config-data
        emptyDir: {}
