apiVersion: v1
kind: Service
metadata:
  name: weatherservice
  labels:
    app: weather
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
  selector:
    app: weather
  type: ClusterIP
