apiVersion: v1
kind: Service
metadata:
  name: weatherservice
  labels:
    app: weather
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: weather
  type: LoadBalancer
