apiVersion: v1
kind: LimitRange
metadata:
  name: default-ns-resource-limits
  namespace: default
spec:
  limits:
  - default:
      cpu: 1
      memory: 2Gi
      ephemeral-storage: 4Gi
    defaultRequest:
      cpu: 250m
      memory: 512Mi
      ephemeral-storage: 1Gi
    type: Container
