name: master-build-push

on:
  push:
    branches:
      - "master"
    paths:
      - "/apps/sinatra/src/**"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get SHA for tagging
        id: sha_tag
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dp-sinatra:${{steps.sha_tag.outputs.short_sha}}
