name: 'Deploy Secrets Store CSI Driver'
on:
  push:
    branches:
      - 'master'
    paths:
      - 'platform/secrets-store-csi-driver/*'

jobs:
  run:
    name: 'Deploy Secrets Store CSI Driver'
    permissions:
      id-token: write
      contents: read
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
        service_account: ${{ secrets.GH_SA_EMAIL }}

    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud container clusters get-credentials private --region=australia-southeast1 --project hexkey

    - id: 'helm-deploy'
      name: 'Use Helm to deploy csi driver'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'csi-secrets-store'
        namespace: 'kube-system'
        chart: 'secrets-store-csi-driver/secrets-store-csi-driver'
        repo: 'https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts'
