name: 'Test Workload Identity'
on:
  push:
    branches:
    - 'master'
jobs:
  run:
    name: 'Test Workload Identity'
    permissions:
      id-token: write
      contents: read
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
        service_account: ${{ secrets.GH_SA_EMAIL }}

    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud container clusters get-credentials private --region=australia-southeast1 --project hexkey

    - id: 'get-kubectl'
      name: 'Get Kubectl'
      uses: actions-hub/kubectl@master
      with:
        args: get pods -n default
